[
  {"code": "USA", "name": "United States", "value": 4.8},
  {"code": "AUS", "name": "Australia", "value": 5.9},
  {"code": "EST", "name": "Estonia", "value": 5.9},
  {"code": "BRA", "name": "Brazil", "value": 5.3},
  {"code": "PRT", "name": "Portugal", "value": 5.7},
  {"code": "GRC", "name": "Greece", "value": 6.0},
  {"code": "IRN", "name": "Iran", "value": 5.1},
  {"code": "FIN", "name": "Finland", "value": 5.6},
  {"code": "SWE", "name": "Sweden", "value": 5.2},
  {"code": "MAR", "name": "Morocco", "value": 4.5},
  {"code": "ESP", "name": "Spain", "value": 5.4},
  {"code": "FRA", "name": "France", "value": 4.6},
  {"code": "DEU", "name": "Germany", "value": 4.3},
  {"code": "ITA", "name": "Italy", "value": 4.1},
  {"code": "GBR", "name": "United Kingdom", "value": 4.5},
  {"code": "UKR", "name": "Ukraine", "value": 6.3},
  {"code": "RUS", "name": "Russia", "value": 3.8},
  {"code": "CHN", "name": "China", "value": 3.4},
  {"code": "IND", "name": "India", "value": 3.5},
  {"code": "JPN", "name": "Japan", "value": 3.2},
  {"code": "CAN", "name": "Canada", "value": 4.5},
  {"code": "ZAF", "name": "South Africa", "value": 4.2},
  {"code": "NGA", "name": "Nigeria", "value": 2.2},
  {"code": "EGY", "name": "Egypt", "value": 3.8},
  {"code": "ARG", "name": "Argentina", "value": 4.3},
  {"code": "CHL", "name": "Chile", "value": 4.3},
  {"code": "MEX", "name": "Mexico", "value": 3.2},
  {"code": "TUR", "name": "Turkey", "value": 4.0},
  {"code": "SAU", "name": "Saudi Arabia", "value": 4.2},
  {"code": "IDN", "name": "Indonesia", "value": 2.6},
  {"code": "KOR", "name": "South Korea", "value": 3.3},
  {"code": "NOR", "name": "Norway", "value": 4.7},
  {"code": "NZL", "name": "New Zealand", "value": 5.2},
  {"code": "GHA", "name": "Ghana", "value": 2.9},
  {"code": "KEN", "name": "Kenya", "value": 3.5},
  {"code": "ETH", "name": "Ethiopia", "value": 4.7},
  {"code": "DZA", "name": "Algeria", "value": 4.5},
  {"code": "PAK", "name": "Pakistan", "value": 3.8},
  {"code": "BGD", "name": "Bangladesh", "value": 3.8},
  {"code": "VNM", "name": "Vietnam", "value": 2.7},
  {"code": "THA", "name": "Thailand", "value": 3.2},
  {"code": "COL", "name": "Colombia", "value": 2.4},
  {"code": "PER", "name": "Peru", "value": 2.6}
]
